// shared/scene-asset-registry.ts
//
// Seed data for the scene-background asset system (design spec §13-14),
// sourced from the 2026-08-17 "DungeonMasterOS Scene Background Asset
// Research Report" (30-item prioritized shortlist + DeviantArt clearance
// queue). No third-party image file has been downloaded or bundled — every
// entry below is metadata only (sourceUrl/creator/license/attribution).
// `localAssetPath` stays unset, so the resolver falls through to the
// procedural gradient until a real file is acquired, verified against the
// report's clearance checklist, and explicitly approved for download.
//
// Only entries the report marks unambiguously "cleared in principle" (a
// CC0 dedication, or an explicit CC BY 3.0 + "commercial premade
// backgrounds allowed" statement, each with a confirmed native resolution)
// carry clearanceStatus "cleared". Everything else — including every
// Pexels/Pixabay candidate, since the report explicitly says their native
// pixel dimensions were never confirmed in this research pass — is
// "pending-technical-verification" and must not be selected by the
// resolver yet.

import type { SceneAsset } from "./scene-assets";

export const SCENE_ASSET_REGISTRY: SceneAsset[] = [
  {
    id: "darkmoon-art-de-eerie-forest-fog",
    sourceUrl:
      "https://www.deviantart.com/darkmoon-art-de/art/Eerie-background-with-trees-and-pathway-fog-free-1215071287",
    creator: "Darkmoon-Art-de",
    clearanceStatus: "cleared",
    license: {
      type: "CC-BY-3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
      checkedAt: "2026-08-17",
      attributionRequired: true,
      attributionText: "\"Eerie background with trees and pathway fog\" by Darkmoon-Art-de, CC BY 3.0, via DeviantArt",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "allowed",
      evidenceSnapshot: "Page displays CC BY 3.0 badge; artist states the piece was made in Photoshop without AI and that commercial use is allowed.",
    },
    technical: {
      originalWidth: 7000,
      originalHeight: 3938,
      landscape: true,
      variants: ["21:9", "16:9", "mobile"],
      checksum: null,
    },
    provenance: { aiGenerated: false, recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "clear" },
    tags: ["forest", "fog", "path", "atmospheric", "horror"],
    genres: ["genre:fantasy", "genre:gothic"],
    environments: ["forest-fog", "wilderness-mist", "fog-supernatural"],
    dayPhase: "dusk",
    weather: ["fog"],
    suitability: { textNoise: "medium", focalPoint: "center", suggestedDim: 38, suggestedVignette: "strong", suggestedBlurPx: 3 },
  },
  {
    id: "boldfrontiers-forest-castle-ruins",
    sourceUrl: "https://www.deviantart.com/boldfrontiers/art/Forest-Castle-Ruins-637326035",
    creator: "boldfrontiers",
    clearanceStatus: "cleared",
    license: {
      type: "CC-BY-3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
      checkedAt: "2026-08-17",
      attributionRequired: true,
      attributionText: "\"Forest Castle Ruins\" by boldfrontiers, CC BY 3.0, via DeviantArt",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "allowed",
      evidenceSnapshot: "Page displays CC BY 3.0 and explicitly states commercial use, including premade backgrounds, is allowed.",
    },
    technical: { originalWidth: 5000, originalHeight: 3333, landscape: true, variants: ["16:9", "4:3", "mobile"], checksum: null },
    provenance: { aiGenerated: false, recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "clear" },
    tags: ["ruins", "castle", "forest"],
    genres: ["genre:fantasy"],
    environments: ["ruins", "castle-exterior", "temple-ruins"],
    dayPhase: "day",
    suitability: { textNoise: "medium", focalPoint: "center", suggestedDim: 40, suggestedVignette: "medium", suggestedBlurPx: 3 },
  },
  {
    id: "boldfrontiers-cades-cove-sunrise",
    sourceUrl: "https://www.deviantart.com/boldfrontiers/art/Cades-Cove-Sunrise-824463893",
    creator: "boldfrontiers",
    clearanceStatus: "cleared",
    license: {
      type: "CC-BY-3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
      checkedAt: "2026-08-17",
      attributionRequired: true,
      attributionText: "\"Cades Cove Sunrise\" by boldfrontiers, CC BY 3.0, via DeviantArt",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "allowed",
      evidenceSnapshot: "Explicit commercial premade-background permission wording, same as the artist's other cleared pieces.",
    },
    technical: { originalWidth: 5000, originalHeight: 3333, landscape: true, variants: ["16:9", "4:3", "mobile"], checksum: null },
    provenance: { aiGenerated: false, recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "clear" },
    tags: ["wilderness", "mist", "hills", "sunrise"],
    genres: ["genre:fantasy"],
    environments: ["wilderness-mist", "wilderness"],
    dayPhase: "day",
    weather: ["mist"],
    suitability: { textNoise: "low", focalPoint: "center", suggestedDim: 35, suggestedVignette: "medium", suggestedBlurPx: 2 },
  },
  {
    id: "boldfrontiers-falls-ridge-cave-trail",
    sourceUrl: "https://www.deviantart.com/boldfrontiers/art/Falls-Ridge-Cave-Trail-804247479",
    creator: "boldfrontiers",
    clearanceStatus: "cleared",
    license: {
      type: "CC-BY-3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
      checkedAt: "2026-08-17",
      attributionRequired: true,
      attributionText: "\"Falls Ridge Cave Trail\" by boldfrontiers, CC BY 3.0, via DeviantArt",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "allowed",
      evidenceSnapshot: "Same explicit CC BY / commercial-premade-background wording as the artist's other cleared pieces.",
    },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: false, recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "clear" },
    tags: ["cave", "forest", "trail"],
    genres: ["genre:fantasy"],
    environments: ["cave", "forest"],
    suitability: { textNoise: "medium", focalPoint: "center", suggestedDim: 32, suggestedVignette: "medium" },
  },
  {
    id: "boldfrontiers-blaenavon-ironworks",
    sourceUrl: "https://www.deviantart.com/boldfrontiers/art/Blaenavon-Ironworks-984459683",
    creator: "boldfrontiers",
    clearanceStatus: "cleared",
    license: {
      type: "CC-BY-3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
      checkedAt: "2026-08-17",
      attributionRequired: true,
      attributionText: "\"Blaenavon Ironworks\" by boldfrontiers, CC BY 3.0, via DeviantArt",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "allowed",
      evidenceSnapshot: "Same explicit CC BY / commercial-premade-background wording as the artist's other cleared pieces.",
    },
    technical: { originalWidth: 5000, originalHeight: 3333, landscape: true, variants: ["16:9", "4:3", "mobile"], checksum: null },
    provenance: { aiGenerated: false, recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "clear" },
    tags: ["ironworks", "industrial", "ruins", "mine"],
    genres: ["genre:fantasy", "genre:post-apocalyptic"],
    environments: ["dungeon", "cave", "ruins"],
    suitability: { textNoise: "medium", focalPoint: "center", suggestedDim: 40, suggestedVignette: "medium" },
  },
  {
    id: "opengameart-large-parchment-texture",
    sourceUrl: "https://lpc.opengameart.org/content/large-parchment-texture",
    creator: "Luke.RUSTLTD",
    clearanceStatus: "cleared",
    license: {
      type: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      attributionText: "Optional: Luke.RUSTLTD / OpenGameArt, CC0",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "allowed",
      evidenceSnapshot: "OpenGameArt asset page lists CC0.",
    },
    technical: {
      originalWidth: 1920,
      originalHeight: 1080,
      landscape: true,
      variants: ["16:9", "4:3", "mobile"],
      checksum: "0ec7531d4636ca5b0d62146892f5ab22588d46d6b67700be45ce3e0f27fd7173",
    },
    provenance: { aiGenerated: false, recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "clear" },
    tags: ["parchment", "texture", "neutral"],
    genres: ["genre:fantasy"],
    environments: [],
    suitability: { textNoise: "low", suggestedDim: 0, suggestedVignette: "light" },
    localAssetPath: "/scene-assets/opengameart-large-parchment-texture.webp",
  },
  {
    id: "opengameart-dark-wood-seamless-texture",
    sourceUrl: "https://opengameart.org/content/dark-wood-seamless-handcrafted-texture",
    creator: "Sams-Creatives",
    clearanceStatus: "cleared",
    license: {
      type: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      commercialUse: true,
      modification: true,
      bundledRedistribution: "allowed",
      evidenceSnapshot: "OpenGameArt asset page lists CC0.",
    },
    technical: {
      originalWidth: 2048,
      originalHeight: 2048,
      landscape: false,
      variants: ["mobile"],
      checksum: "9d712ef2db24e6595a46da536c45aec75f9e4dbf179adcba0f86f1a52c4aa0b2",
    },
    provenance: { aiGenerated: false, recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "clear" },
    tags: ["wood", "texture", "neutral", "seamless"],
    genres: ["genre:fantasy"],
    environments: [],
    suitability: { textNoise: "low", suggestedDim: 0, suggestedVignette: "light" },
    localAssetPath: "/scene-assets/opengameart-dark-wood-seamless-texture.webp",
  },
  {
    id: "kenney-pattern-pack-01",
    sourceUrl: "https://kenney.nl/assets/pattern-pack",
    creator: "Kenney",
    clearanceStatus: "cleared",
    license: {
      type: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      attributionText: "Optional: Kenney.nl",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "allowed",
      evidenceSnapshot: "Kenney states all game assets on its asset pages are CC0. Pattern Pack contains 80 tiles; this entry uses tile 01 as the representative seed — the other 79 are not yet ingested.",
    },
    technical: {
      originalWidth: 256,
      originalHeight: 256,
      landscape: false,
      variants: ["mobile"],
      checksum: "1433da82e5c764355e85f9a7c4599711006115c7fd165ac1eda1a52b1250fbfe",
    },
    provenance: { aiGenerated: false, recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "clear" },
    tags: ["pattern", "vignette-base", "neutral", "tile-01-of-80"],
    genres: ["genre:fantasy"],
    environments: [],
    suitability: { textNoise: "low", suggestedDim: 0, suggestedVignette: "light" },
    localAssetPath: "/scene-assets/kenney-pattern-pack.webp",
  },

  // -- Pending technical verification: Pixabay entries with a confirmed
  //    resolution but not yet checksummed/acquired. License terms permit
  //    commercial use as an integrated application derivative (never a
  //    standalone stock download), per the report's Pixabay guidance.
  {
    id: "pixabay-old-town-twilight",
    sourceUrl: "https://pixabay.com/photos/old-town-buildings-street-twilight-6300696/",
    creator: "TomasHa73",
    clearanceStatus: "pending-technical-verification",
    license: {
      type: "PIXABAY",
      licenseUrl: "https://pixabay.com/service/license-summary/",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      attributionText: "Photo: TomasHa73 / Pixabay",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "conditional",
      evidenceSnapshot: "Pixabay Content License permits commercial use/adaptation but restricts standalone stock-style redistribution; ship only as a processed application derivative.",
    },
    technical: { originalWidth: 5472, originalHeight: 3648, landscape: true, variants: ["16:9", "4:3"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["market", "street", "old-town", "twilight"],
    genres: ["genre:fantasy", "genre:gothic"],
    environments: ["city-street", "busy-market"],
    dayPhase: "dusk",
    suitability: { textNoise: "high", suggestedDim: 44, suggestedVignette: "medium", suggestedBlurPx: 4 },
  },
  {
    id: "pixabay-street-of-knights-medieval",
    sourceUrl: "https://pixabay.com/photos/street-of-knights-street-medieval-7154135/",
    creator: "dimitrisvetsikas1969",
    clearanceStatus: "pending-technical-verification",
    license: {
      type: "PIXABAY",
      licenseUrl: "https://pixabay.com/service/license-summary/",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      attributionText: "Photo: dimitrisvetsikas1969 / Pixabay",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "conditional",
      evidenceSnapshot: "Pixabay Content License; ship only as a processed application derivative.",
    },
    technical: { originalWidth: 4223, originalHeight: 2375, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["market", "street", "medieval"],
    genres: ["genre:fantasy"],
    environments: ["city-street", "busy-market"],
    suitability: { textNoise: "high", suggestedDim: 44, suggestedVignette: "medium", suggestedBlurPx: 4 },
  },
  {
    id: "pixabay-cave-gallery-dungeon-stones",
    sourceUrl: "https://pixabay.com/photos/cave-gallery-dungeon-stones-1880282/",
    creator: "DenisPet",
    clearanceStatus: "pending-technical-verification",
    license: {
      type: "PIXABAY",
      licenseUrl: "https://pixabay.com/service/license-summary/",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      attributionText: "Photo: DenisPet / Pixabay",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "conditional",
      evidenceSnapshot: "Pixabay Content License; ship only as a processed application derivative.",
    },
    technical: { originalWidth: 6000, originalHeight: 4000, landscape: true, variants: ["16:9", "4:3"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["cave", "dungeon", "gallery"],
    genres: ["genre:fantasy"],
    environments: ["cave", "dungeon"],
    suitability: { textNoise: "low", suggestedDim: 28, suggestedVignette: "medium", suggestedBlurPx: 3 },
  },
  {
    id: "pixabay-cave-quarry-dungeon-candles",
    sourceUrl: "https://pixabay.com/photos/cave-quarry-dungeon-dark-gallery-2132899/",
    creator: "ksilo",
    clearanceStatus: "pending-technical-verification",
    license: {
      type: "PIXABAY",
      licenseUrl: "https://pixabay.com/service/license-summary/",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      attributionText: "Photo: ksilo / Pixabay",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "conditional",
      evidenceSnapshot: "Pixabay Content License; ship only as a processed application derivative.",
    },
    technical: { originalWidth: 5184, originalHeight: 3456, landscape: true, variants: ["16:9", "4:3"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["cave", "dungeon", "quarry", "candles"],
    genres: ["genre:fantasy"],
    environments: ["cave", "crypt", "dungeon"],
    dayPhase: "night",
    suitability: { textNoise: "low", suggestedDim: 28, suggestedVignette: "medium", suggestedBlurPx: 3 },
  },
  {
    id: "pixabay-castle-fortress-medieval-stone",
    sourceUrl: "https://pixabay.com/photos/castle-fortress-medieval-stone-9730990/",
    creator: "the_iop",
    clearanceStatus: "pending-technical-verification",
    license: {
      type: "PIXABAY",
      licenseUrl: "https://pixabay.com/service/license-summary/",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      attributionText: "Photo: the_iop / Pixabay",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "conditional",
      evidenceSnapshot: "Pixabay Content License; ship only as a processed application derivative.",
    },
    technical: { originalWidth: 7023, originalHeight: 4682, landscape: true, variants: ["16:9", "4:3"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["castle", "fortress", "medieval", "stone"],
    genres: ["genre:fantasy"],
    environments: ["castle-exterior", "castle-interior"],
    suitability: { textNoise: "medium", suggestedDim: 40, suggestedVignette: "medium", suggestedBlurPx: 3 },
  },
  {
    id: "pixabay-castle-mountains-forest-fog",
    sourceUrl: "https://pixabay.com/photos/castle-mountains-forest-fog-9198810/",
    creator: "Nordseher",
    clearanceStatus: "pending-technical-verification",
    license: {
      type: "PIXABAY",
      licenseUrl: "https://pixabay.com/service/license-summary/",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      attributionText: "Photo: Nordseher / Pixabay",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "conditional",
      evidenceSnapshot: "Pixabay Content License; ship only as a processed application derivative.",
    },
    technical: { originalWidth: 5279, originalHeight: 3520, landscape: true, variants: ["16:9", "4:3"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["castle", "mountains", "forest", "fog"],
    genres: ["genre:fantasy", "genre:gothic"],
    environments: ["castle-fog", "mountain-road"],
    weather: ["fog"],
    suitability: { textNoise: "medium", suggestedDim: 38, suggestedVignette: "strong", suggestedBlurPx: 3 },
  },

  // -- Pending technical verification: Pexels entries. The report is
  //    explicit that Pexels' public pages generally did not expose native
  //    pixel dimensions in this research pass, so these fail the
  //    production ingestion gate until re-checked at acquisition.
  {
    id: "pexels-nordic-shed-fireplace",
    sourceUrl: "https://www.pexels.com/photo/interior-of-traditional-old-nordic-shed-with-burning-fireplace-5023730/",
    creator: "Erik Mclean",
    clearanceStatus: "pending-technical-verification",
    license: {
      type: "PEXELS",
      licenseUrl: "https://www.pexels.com/legal-pages/license/",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      attributionText: "Photo: Erik Mclean / Pexels",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "conditional",
      evidenceSnapshot: "Pexels License; ship only as a processed application derivative, native resolution unverified.",
    },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["tavern", "inn", "fireplace", "interior"],
    genres: ["genre:fantasy"],
    environments: ["tavern"],
    suitability: { textNoise: "low", suggestedDim: 36, suggestedVignette: "medium", suggestedBlurPx: 3 },
  },
  {
    id: "pexels-rustic-home-interior-fireplace",
    sourceUrl: "https://www.pexels.com/photo/a-home-interior-7746099/",
    creator: "Max Vakhtbovych",
    clearanceStatus: "pending-technical-verification",
    license: {
      type: "PEXELS",
      licenseUrl: "https://www.pexels.com/legal-pages/license/",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      commercialUse: true,
      modification: true,
      bundledRedistribution: "conditional",
      evidenceSnapshot: "Pexels License; native resolution unverified.",
    },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["tavern", "inn", "fireplace", "interior"],
    genres: ["genre:fantasy"],
    environments: ["tavern", "tavern-night"],
    suitability: { textNoise: "low", suggestedDim: 36, suggestedVignette: "medium", suggestedBlurPx: 3 },
  },
  {
    id: "pexels-enchanting-forest-path-mist",
    sourceUrl: "https://www.pexels.com/photo/enchanting-forest-path-with-morning-mist-29451794/",
    creator: "Thomas P",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["forest", "mist", "day"],
    genres: ["genre:fantasy"],
    environments: ["forest"],
    dayPhase: "day",
    weather: ["mist"],
    suitability: { textNoise: "medium", suggestedDim: 38, suggestedVignette: "medium", suggestedBlurPx: 2 },
  },
  {
    id: "pexels-moon-above-forest-night",
    sourceUrl: "https://www.pexels.com/photo/moon-above-forest-during-night-time-1685543/",
    creator: "Egor Kamelev",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["forest", "night", "moon"],
    genres: ["genre:fantasy"],
    environments: ["forest-night"],
    dayPhase: "night",
    suitability: { textNoise: "low", suggestedDim: 30, suggestedVignette: "strong", suggestedBlurPx: 2 },
  },
  {
    id: "pexels-rolling-hills-wilderness",
    sourceUrl: "https://www.pexels.com/photo/36702537",
    creator: "Adrien Olichon",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["wilderness", "fields", "hills"],
    genres: ["genre:fantasy"],
    environments: ["wilderness"],
    dayPhase: "day",
    suitability: { textNoise: "low", suggestedDim: 35, suggestedVignette: "medium" },
  },
  {
    id: "pexels-siena-skyline-dusk",
    sourceUrl: "https://www.pexels.com/photo/scenic-view-of-siena-city-skyline-at-dusk-36742440/",
    creator: "Mert Tuncer",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified, panoramic framing." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["21:9", "16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["city", "skyline", "dusk"],
    genres: ["genre:fantasy", "genre:gothic"],
    environments: ["city-skyline"],
    dayPhase: "dusk",
    suitability: { textNoise: "low", suggestedDim: 42, suggestedVignette: "medium" },
  },
  {
    id: "pexels-coastal-harbor-boats",
    sourceUrl: "https://www.pexels.com/photo/serene-coastal-harbor-with-moored-boats-33564860/",
    creator: "David Pryke",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["coast", "harbor", "boats"],
    genres: ["genre:fantasy"],
    environments: ["coast", "harbor"],
    suitability: { textNoise: "low", suggestedDim: 44, suggestedVignette: "medium" },
  },
  {
    id: "pexels-foggy-marsh",
    sourceUrl: "https://www.pexels.com/photo/foggy-marsh-14549469/",
    creator: "Johannes Plenio",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["swamp", "marsh", "fog"],
    genres: ["genre:fantasy"],
    environments: ["swamp"],
    weather: ["fog"],
    suitability: { textNoise: "low", suggestedDim: 40, suggestedVignette: "medium" },
  },
  {
    id: "pexels-rocky-mountain-pathway",
    sourceUrl: "https://www.pexels.com/photo/rocky-pathway-on-mountainside-15189868/",
    creator: "Just a Dream Pictures",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["mountain", "pathway"],
    genres: ["genre:fantasy"],
    environments: ["mountain-road"],
    suitability: { textNoise: "medium", suggestedDim: 38, suggestedVignette: "medium" },
  },
  {
    id: "pexels-ancient-temple-ruins",
    sourceUrl: "https://www.pexels.com/photo/6422200/",
    creator: "ROMAN ODINTSOV",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["temple", "ruins"],
    genres: ["genre:fantasy"],
    environments: ["temple-ruins", "ruins"],
    suitability: { textNoise: "medium", suggestedDim: 42, suggestedVignette: "medium" },
  },
  {
    id: "pexels-temple-ruins-summer-landscape",
    sourceUrl: "https://www.pexels.com/photo/ancient-ruins-of-temple-in-summer-landscape-32761514/",
    creator: "Mustafa Akin",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["temple", "ruins", "summer"],
    genres: ["genre:fantasy"],
    environments: ["temple-ruins", "ruins"],
    dayPhase: "day",
    suitability: { textNoise: "medium", suggestedDim: 42, suggestedVignette: "medium" },
  },
  {
    id: "pexels-campsite-fire-forest-night",
    sourceUrl: "https://www.pexels.com/photo/campsite-with-flaming-fire-in-forest-at-night-5523762/",
    creator: "K",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["camp", "campfire", "forest", "night"],
    genres: ["genre:fantasy"],
    environments: ["forest-camp"],
    dayPhase: "night",
    suitability: { textNoise: "low", suggestedDim: 28, suggestedVignette: "strong" },
  },
  {
    id: "pexels-snowy-winter-frosted-forest",
    sourceUrl: "https://www.pexels.com/photo/snowy-winter-landscape-with-frosted-forest-36209474/",
    creator: "Elina Volkova",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["snow", "winter", "forest"],
    genres: ["genre:fantasy"],
    environments: ["snow"],
    weather: ["snow"],
    suitability: { textNoise: "high", suggestedDim: 55, suggestedVignette: "medium", suggestedBlurPx: 5 },
  },
  {
    id: "pexels-golden-sand-dunes-desert",
    sourceUrl: "https://www.pexels.com/photo/golden-sand-dunes-in-desert-landscape-28639324/",
    creator: "Stephen Leonardi",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["desert", "dunes"],
    genres: ["genre:fantasy"],
    environments: ["desert"],
    dayPhase: "day",
    suitability: { textNoise: "medium", suggestedDim: 45, suggestedVignette: "medium", suggestedBlurPx: 4 },
  },
  {
    id: "pexels-misty-night-glow-fog",
    sourceUrl: "https://www.pexels.com/photo/misty-night-landscape-with-glow-in-fog-34648532/",
    creator: "iilushk0",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["fog", "supernatural", "night", "glow"],
    genres: ["genre:fantasy", "genre:gothic"],
    environments: ["fog-supernatural"],
    dayPhase: "night",
    weather: ["fog"],
    suitability: { textNoise: "low", suggestedDim: 50, suggestedVignette: "medium", suggestedBlurPx: 4 },
  },
  {
    id: "pexels-thunderstorm-night",
    sourceUrl: "https://www.pexels.com/photo/thunderstorm-at-night-14174222/",
    creator: "Anton Kudryashov",
    clearanceStatus: "pending-technical-verification",
    license: { type: "PEXELS", licenseUrl: "https://www.pexels.com/legal-pages/license/", checkedAt: "2026-08-17", attributionRequired: false, commercialUse: true, modification: true, bundledRedistribution: "conditional", evidenceSnapshot: "Pexels License; native resolution unverified." },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["16:9"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["storm", "night", "lightning"],
    genres: ["genre:fantasy", "genre:gothic"],
    environments: ["storm-night"],
    dayPhase: "night",
    weather: ["storm"],
    suitability: { textNoise: "medium", suggestedDim: 34, suggestedVignette: "strong", suggestedBlurPx: 2 },
  },
  {
    id: "unsplash-brown-leather-texture",
    sourceUrl: "https://unsplash.com/photos/brown-leather-xJkTCbtuqAY",
    creator: "Felipe Santana",
    clearanceStatus: "pending-technical-verification",
    license: {
      type: "UNSPLASH",
      licenseUrl: "https://unsplash.com/license",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      attributionText: "Optional: Photo by Felipe Santana on Unsplash",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "allowed",
      evidenceSnapshot: "Unsplash License grants broad commercial rights; native resolution not confirmed at ingestion.",
    },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["mobile"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["leather", "texture", "neutral"],
    genres: ["genre:fantasy"],
    environments: [],
    suitability: { textNoise: "low", suggestedDim: 0, suggestedVignette: "light" },
  },
  {
    id: "unsplash-aged-parchment-paper-texture",
    sourceUrl: "https://unsplash.com/photos/aged-beige-parchment-paper-texture-_YgmNICHdss",
    creator: "Safwan Thottoli",
    clearanceStatus: "pending-technical-verification",
    license: {
      type: "UNSPLASH",
      licenseUrl: "https://unsplash.com/license",
      checkedAt: "2026-08-17",
      attributionRequired: false,
      attributionText: "Optional: Photo by Safwan Thottoli on Unsplash",
      commercialUse: true,
      modification: true,
      bundledRedistribution: "allowed",
      evidenceSnapshot: "Unsplash License grants broad commercial rights; native resolution not confirmed at ingestion.",
    },
    technical: { originalWidth: null, originalHeight: null, landscape: true, variants: ["mobile"], checksum: null },
    provenance: { aiGenerated: "unknown", recognizablePeople: false, trademarksOrLogos: false, propertyRightsReview: "review" },
    tags: ["parchment", "paper", "texture", "neutral"],
    genres: ["genre:fantasy"],
    environments: [],
    suitability: { textNoise: "low", suggestedDim: 0, suggestedVignette: "light" },
  },
];

// Known-blocked or permission-pending DeviantArt candidates from the
// research report's clearance queue. Recorded so they are never silently
// re-proposed; the resolver never reads this list.
export const BLOCKED_CANDIDATES: Array<{ id: string; sourceUrl: string; creator: string; reason: string }> = [
  {
    id: "simbores-room-castle-02",
    sourceUrl: "https://www.deviantart.com/simbores/art/Room-castle-02-481378327",
    creator: "Simbores",
    reason: "License conflict: creator's prose allows commercial use, but the displayed badge is CC BY-NC 3.0. Requires written clarification before use.",
  },
  {
    id: "foxstox-creepy-country-road",
    sourceUrl: "https://www.deviantart.com/foxstox/art/Creepy-Country-Road-276189128",
    creator: "FoxStox",
    reason: "Conditional: creator permits commercial use but prohibits reposting as standalone stock and requires genuinely creative use, not minor edits. Needs a direct clearance note before use.",
  },
  {
    id: "simbores-monument-cut-out-03",
    sourceUrl: "https://www.deviantart.com/simbores/art/Monument-cut-out-03-496030963",
    creator: "Simbores",
    reason: "Potentially cleared but useful only as compositing material, not a complete scene; archive full stock rules before use.",
  },
  {
    id: "bloodguardstock-bloody-parchment-texture",
    sourceUrl: "https://www.deviantart.com/bloodguardstock/art/STOCK-Bloody-Parchment-Texture-Background-613389674",
    creator: "BloodguardStock",
    reason: "Personal-use license by default; page explicitly requires contacting the creator to extend to commercial projects. Permission not yet obtained.",
  },
  {
    id: "ladyxboleyn-warwick-graveyard-52",
    sourceUrl: "https://www.deviantart.com/ladyxboleyn/art/Warwick-Graveyard-52-269194388",
    creator: "LadyxBoleyn",
    reason: "Rights unresolved and technical fail (resolution below the 1920x1080 baseline). Do not use for the core library.",
  },
  {
    id: "drechenaux-haunted-mansion-vn-background",
    sourceUrl: "https://www.deviantart.com/drechenaux/art/Haunted-Mansion-VN-Background-974291465",
    creator: "drechenaux",
    reason: "Commercial use requires prior contact with the creator; source is portrait orientation. Administrative burden disproportionate to value; only pursue with a simple written license.",
  },
  {
    id: "drechenaux-japanese-castle-vn-background",
    sourceUrl: "https://www.deviantart.com/drechenaux/art/Japanese-Castle-VN-Background-Free-To-Use-940174746",
    creator: "drechenaux",
    reason: "Below the requested 1920x1080 baseline; do not upscale for the core library.",
  },
  {
    id: "temporalstasisadopts-swampy-tropical-river",
    sourceUrl: "https://www.deviantart.com/temporalstasisadopts/art/Free-Swampy-Tropical-River-Backgrounds-982612770",
    creator: "TemporalStasisAdopts",
    reason: "Explicitly Midjourney/Photoshop AI-generated with a required AI-disclosure obligation in the finished work; a human-created alternative is preferable for core art.",
  },
  {
    id: "barefootliam-stock-castle-interior-door-1",
    sourceUrl: "https://www.deviantart.com/barefootliam-stock/art/castle-interior-door-1-56130367",
    creator: "barefootliam-stock",
    reason: "Rejected: unusual creator-specific conditions plus source is too small/portrait for the landscape requirement.",
  },
];
