import type { Dnd35SourceRef, Dnd35SpellDefinition } from "../types";

const srd = (section: string): Dnd35SourceRef => ({
  sourceId: "srd-35",
  sourceKind: "srd-open",
  section,
  confidence: "verified",
});

const access = (
  classId: string,
  level: 0|1|2|3|4|5|6|7|8|9,
  tradition: "arcane"|"divine",
  source: Dnd35SourceRef,
) => ({ classId, level, tradition, source });

const commonMaterial = (description: string) => ({
  kind: "M" as const,
  required: true,
  consumed: true,
  description,
});

export const DND35_CORE_SRD_COMBAT_SPELLS: Dnd35SpellDefinition[] = [
  {
    id: "grease",
    name: "Grease",
    edition: "3.5e",
    school: "conjuration",
    subschool: "creation",
    classAccess: [
      access("bard", 1, "arcane", srd("Grease")),
      access("sorcerer", 1, "arcane", srd("Grease")),
      access("wizard", 1, "arcane", srd("Grease")),
    ],
    castingTime: { kind: "standard" },
    components: [
      { kind: "V", required: true },
      { kind: "S", required: true },
      commonMaterial("Non-costly material component; normally supplied by a spell component pouch."),
    ],
    range: { kind: "close", baseFeet: 25, feetPerCasterLevel: 2.5 },
    targeting: {
      delivery: ["area", "target"],
      targetText: "One object",
      areaText: "10-foot square",
      lineOfEffectRequired: true,
      lineOfSightRequired: true,
      objectAllowed: true,
    },
    duration: { kind: "rounds_per_level", dismissible: true },
    savingThrow: { type: "special", repeated: true, text: "Reflex saves apply as described by the surface/object mode; creatures in the area may make repeated saves while exposed." },
    spellResistance: { applies: false },
    attackRoll: "none",
    effects: [
      { effectId: "grease-fall", kind: "condition", conditionId: "prone", saveApplies: true, tags: ["surface", "repeat-save"] },
      { effectId: "grease-object", kind: "control", saveApplies: true, tags: ["object", "disarm-like"] },
      { effectId: "grease-escape", kind: "modifier", modifierType: "circumstance", targetStat: "escape-artist-and-grapple-escape", value: 10, tags: ["conditional"] },
    ],
    rulesSummary: "Creates a slippery 10-foot square or coats one object. Creatures may fall or lose movement, and a greased held object may be dropped; exposed creatures can face repeated checks or saves while the spell lasts.",
    specialRules: [
      "Moving through a greased surface is difficult and uses the Balance rules described by the spell.",
      "Greased armor or clothing grants a +10 circumstance bonus on Escape Artist checks and grapple checks made to resist or escape a grapple or pin.",
    ],
    sources: [srd("Grease")],
    tags: ["core", "srd", "arcane", "battlefield-control", "surface", "object"],
  },
  {
    id: "sleep",
    name: "Sleep",
    edition: "3.5e",
    school: "enchantment",
    subschool: "compulsion",
    descriptors: ["mind-affecting"],
    classAccess: [
      access("bard", 1, "arcane", srd("Sleep")),
      access("sorcerer", 1, "arcane", srd("Sleep")),
      access("wizard", 1, "arcane", srd("Sleep")),
    ],
    castingTime: { kind: "rounds", amount: 1 },
    components: [
      { kind: "V", required: true },
      { kind: "S", required: true },
      commonMaterial("Non-costly material component; normally supplied by a spell component pouch."),
    ],
    range: { kind: "medium", baseFeet: 100, feetPerCasterLevel: 10 },
    targeting: {
      delivery: ["area", "burst"],
      areaText: "Living creatures within a 10-foot-radius burst",
      radiusFeet: 10,
      lineOfEffectRequired: true,
      lineOfSightRequired: false,
      creatureTypes: ["living"],
      objectAllowed: false,
    },
    duration: { kind: "minutes_per_level" },
    savingThrow: { type: "will", outcome: "negates" },
    spellResistance: { applies: true },
    attackRoll: "none",
    effects: [
      { effectId: "magical-sleep", kind: "condition", conditionId: "asleep", saveApplies: true, spellResistanceApplies: true, tags: ["helpless", "hd-limited"] },
    ],
    rulesSummary: "Puts up to 4 Hit Dice of living creatures to sleep, affecting the lowest-HD eligible creatures first. Affected creatures are helpless until awakened or the duration ends.",
    specialRules: [
      "Affects a total of 4 Hit Dice, beginning with creatures that have the fewest Hit Dice.",
      "Does not affect unconscious creatures, constructs, or undead.",
      "Wounding or a standard-action awakening attempt ends the sleep for that creature; ordinary noise does not.",
    ],
    sources: [srd("Sleep")],
    tags: ["core", "srd", "arcane", "mind-affecting", "control", "hd-limited"],
  },
  {
    id: "mage-armor",
    name: "Mage Armor",
    edition: "3.5e",
    school: "conjuration",
    subschool: "creation",
    descriptors: ["force"],
    classAccess: [
      access("sorcerer", 1, "arcane", srd("Mage Armor")),
      access("wizard", 1, "arcane", srd("Mage Armor")),
    ],
    castingTime: { kind: "standard" },
    components: [
      { kind: "V", required: true },
      { kind: "S", required: true },
      { kind: "F", required: true, description: "A small cured-leather focus.", itemTags: ["mage-armor-focus"] },
    ],
    range: { kind: "touch" },
    targeting: { delivery: ["melee_touch"], targetText: "Creature touched", lineOfEffectRequired: true, lineOfSightRequired: false, objectAllowed: false },
    duration: { kind: "hours_per_level", dismissible: true },
    savingThrow: { type: "will", outcome: "harmless", harmless: true },
    spellResistance: { applies: false, harmless: true },
    attackRoll: "melee_touch",
    effects: [
      { effectId: "mage-armor-ac", kind: "modifier", modifierType: "armor", targetStat: "ac", value: 4, tags: ["force", "nonstacking-armor-bonus"] },
    ],
    rulesSummary: "Surrounds the touched creature with a force effect that grants a +4 armor bonus to AC without armor check penalty, speed reduction, or arcane spell failure.",
    specialRules: ["Because it is a force effect, its AC benefit applies against incorporeal touch attacks."],
    sources: [srd("Mage Armor")],
    tags: ["core", "srd", "arcane", "force", "defense", "ac"],
  },
  {
    id: "shield",
    name: "Shield",
    edition: "3.5e",
    school: "abjuration",
    descriptors: ["force"],
    classAccess: [
      access("sorcerer", 1, "arcane", srd("Shield")),
      access("wizard", 1, "arcane", srd("Shield")),
    ],
    castingTime: { kind: "standard" },
    components: [{ kind: "V", required: true }, { kind: "S", required: true }],
    range: { kind: "personal" },
    targeting: { delivery: ["personal"], targetText: "You", objectAllowed: false },
    duration: { kind: "minutes_per_level", dismissible: true },
    savingThrow: { type: "none" },
    spellResistance: { applies: false },
    attackRoll: "none",
    effects: [
      { effectId: "shield-ac", kind: "modifier", modifierType: "shield", targetStat: "ac", value: 4, tags: ["force", "nonstacking-shield-bonus"] },
      { effectId: "shield-magic-missile", kind: "special", tags: ["magic-missile-immunity"], rulesNote: "Negates magic missile attacks directed at the protected caster." },
    ],
    rulesSummary: "Creates a mobile force shield granting a +4 shield bonus to AC and negating magic missile attacks directed at you.",
    specialRules: ["The shield bonus applies against incorporeal touch attacks and does not impose armor check penalty or arcane spell failure."],
    sources: [srd("Shield")],
    tags: ["core", "srd", "arcane", "force", "defense", "ac", "magic-missile-counter"],
  },
  {
    id: "burning-hands",
    name: "Burning Hands",
    edition: "3.5e",
    school: "evocation",
    descriptors: ["fire"],
    classAccess: [
      access("sorcerer", 1, "arcane", srd("Burning Hands")),
      access("wizard", 1, "arcane", srd("Burning Hands")),
    ],
    domainAccess: [{ domainId: "fire", level: 1, source: srd("Fire Domain") }],
    castingTime: { kind: "standard" },
    components: [{ kind: "V", required: true }, { kind: "S", required: true }],
    range: { kind: "fixed", feet: 15 },
    targeting: { delivery: ["area", "cone", "burst"], areaText: "15-foot cone-shaped burst", lengthFeet: 15, lineOfEffectRequired: true, lineOfSightRequired: false, objectAllowed: true },
    duration: { kind: "instantaneous" },
    savingThrow: { type: "reflex", outcome: "half" },
    spellResistance: { applies: true },
    attackRoll: "none",
    effects: [
      { effectId: "burning-hands-fire", kind: "damage", damageType: "fire", dice: "1d4/caster level", scaling: [{ field: "damageDice", operation: "dice", perCasterLevels: 1, dice: "1d4", maximum: 5 }], saveApplies: true, spellResistanceApplies: true, tags: ["area-damage"] },
      { effectId: "ignite-flammables", kind: "special", tags: ["environment", "flammable-objects"], rulesNote: "Flammable materials touched by the flames may ignite." },
    ],
    rulesSummary: "A 15-foot cone deals 1d4 fire damage per caster level, maximum 5d4. Reflex halves the damage and spell resistance applies.",
    sources: [srd("Burning Hands"), srd("Fire Domain")],
    tags: ["core", "srd", "arcane", "fire", "area", "direct-damage"],
  },
  {
    id: "scorching-ray",
    name: "Scorching Ray",
    edition: "3.5e",
    school: "evocation",
    descriptors: ["fire"],
    classAccess: [
      access("sorcerer", 2, "arcane", srd("Scorching Ray")),
      access("wizard", 2, "arcane", srd("Scorching Ray")),
    ],
    castingTime: { kind: "standard" },
    components: [{ kind: "V", required: true }, { kind: "S", required: true }],
    range: { kind: "close", baseFeet: 25, feetPerCasterLevel: 2.5 },
    targeting: { delivery: ["ray", "ranged_touch", "effect"], effectText: "One or more rays", maxTargets: 3, lineOfEffectRequired: true, lineOfSightRequired: true, objectAllowed: true },
    duration: { kind: "instantaneous" },
    savingThrow: { type: "none" },
    spellResistance: { applies: true },
    attackRoll: "ranged_touch",
    effects: [
      { effectId: "scorching-rays", kind: "damage", damageType: "fire", dice: "4d6 per ray", scaling: [{ field: "rayCount", operation: "step", perCasterLevels: 4, minimum: 1, maximum: 3, text: "One ray initially, a second at caster level 7, and a third at caster level 11." }], spellResistanceApplies: true, tags: ["ray", "multiple-projectiles"] },
    ],
    rulesSummary: "Fires one to three rays depending on caster level. Each ray requires a ranged touch attack and deals 4d6 fire damage; no saving throw applies.",
    specialRules: ["All rays are fired simultaneously and their targets must be within 30 feet of one another."],
    sources: [srd("Scorching Ray")],
    tags: ["core", "srd", "arcane", "fire", "ray", "direct-damage", "ranged-touch"],
  },
  {
    id: "lightning-bolt",
    name: "Lightning Bolt",
    edition: "3.5e",
    school: "evocation",
    descriptors: ["electricity"],
    classAccess: [
      access("sorcerer", 3, "arcane", srd("Lightning Bolt")),
      access("wizard", 3, "arcane", srd("Lightning Bolt")),
    ],
    castingTime: { kind: "standard" },
    components: [
      { kind: "V", required: true },
      { kind: "S", required: true },
      commonMaterial("Non-costly material component; normally supplied by a spell component pouch."),
    ],
    range: { kind: "fixed", feet: 120 },
    targeting: { delivery: ["area", "line"], areaText: "120-foot line", lengthFeet: 120, lineOfEffectRequired: true, lineOfSightRequired: false, objectAllowed: true },
    duration: { kind: "instantaneous" },
    savingThrow: { type: "reflex", outcome: "half" },
    spellResistance: { applies: true },
    attackRoll: "none",
    effects: [
      { effectId: "lightning-damage", kind: "damage", damageType: "electricity", dice: "1d6/caster level", scaling: [{ field: "damageDice", operation: "dice", perCasterLevels: 1, dice: "1d6", maximum: 10 }], saveApplies: true, spellResistanceApplies: true, tags: ["line-damage"] },
      { effectId: "lightning-objects", kind: "special", tags: ["objects", "environment"], rulesNote: "The bolt can ignite combustibles and damage objects in its path; barriers can stop or be broken through according to damage and remaining range." },
    ],
    rulesSummary: "A 120-foot line deals 1d6 electricity damage per caster level, maximum 10d6. Reflex halves the damage and spell resistance applies.",
    sources: [srd("Lightning Bolt")],
    tags: ["core", "srd", "arcane", "electricity", "line", "direct-damage"],
  },
  {
    id: "haste",
    name: "Haste",
    edition: "3.5e",
    school: "transmutation",
    classAccess: [
      access("bard", 3, "arcane", srd("Haste")),
      access("sorcerer", 3, "arcane", srd("Haste")),
      access("wizard", 3, "arcane", srd("Haste")),
    ],
    castingTime: { kind: "standard" },
    components: [
      { kind: "V", required: true },
      { kind: "S", required: true },
      commonMaterial("Non-costly material component; normally supplied by a spell component pouch."),
    ],
    range: { kind: "close", baseFeet: 25, feetPerCasterLevel: 2.5 },
    targeting: { delivery: ["target"], targetText: "One creature per caster level, with all targets within 30 feet of one another", maxTargetsPerCasterLevel: 1, lineOfEffectRequired: true, lineOfSightRequired: true, objectAllowed: false },
    duration: { kind: "rounds_per_level" },
    savingThrow: { type: "fortitude", outcome: "harmless", harmless: true },
    spellResistance: { applies: true, harmless: true },
    attackRoll: "none",
    effects: [
      { effectId: "haste-extra-attack", kind: "special", tags: ["full-attack", "extra-attack"], rulesNote: "When making a full attack, a hasted creature gains one extra weapon attack at its full base attack bonus; this does not grant an extra action." },
      { effectId: "haste-attack", kind: "modifier", modifierType: "untyped", targetStat: "attack-rolls", value: 1 },
      { effectId: "haste-ac", kind: "modifier", modifierType: "dodge", targetStat: "ac", value: 1 },
      { effectId: "haste-reflex", kind: "modifier", modifierType: "dodge", targetStat: "reflex-save", value: 1 },
      { effectId: "haste-speed", kind: "movement", value: 30, tags: ["enhancement", "all-movement-modes"], rulesNote: "Each movement mode increases by 30 feet, capped at twice the subject's normal speed for that mode." },
    ],
    counterspells: ["slow"],
    rulesSummary: "Speeds one creature per caster level: one extra weapon attack during a full attack, +1 on attacks, +1 dodge AC and Reflex saves, and +30 feet to movement modes subject to the spell's doubling cap.",
    specialRules: ["Multiple haste effects do not stack.", "Haste counters and dispels slow."],
    sources: [srd("Haste")],
    tags: ["core", "srd", "arcane", "buff", "speed", "extra-attack"],
  },
  {
    id: "slow",
    name: "Slow",
    edition: "3.5e",
    school: "transmutation",
    classAccess: [
      access("bard", 3, "arcane", srd("Slow")),
      access("sorcerer", 3, "arcane", srd("Slow")),
      access("wizard", 3, "arcane", srd("Slow")),
    ],
    castingTime: { kind: "standard" },
    components: [
      { kind: "V", required: true },
      { kind: "S", required: true },
      commonMaterial("Non-costly material component; normally supplied by a spell component pouch."),
    ],
    range: { kind: "close", baseFeet: 25, feetPerCasterLevel: 2.5 },
    targeting: { delivery: ["target"], targetText: "One creature per caster level, with all targets within 30 feet of one another", maxTargetsPerCasterLevel: 1, lineOfEffectRequired: true, lineOfSightRequired: true, objectAllowed: false },
    duration: { kind: "rounds_per_level" },
    savingThrow: { type: "will", outcome: "negates" },
    spellResistance: { applies: true },
    attackRoll: "none",
    effects: [
      { effectId: "slow-action-limit", kind: "special", saveApplies: true, spellResistanceApplies: true, tags: ["action-economy"], rulesNote: "A slowed creature may take only a single move action or standard action each turn, not both, and cannot take full-round actions." },
      { effectId: "slow-attack", kind: "modifier", modifierType: "penalty", targetStat: "attack-rolls", value: -1, saveApplies: true },
      { effectId: "slow-ac", kind: "modifier", modifierType: "penalty", targetStat: "ac", value: -1, saveApplies: true },
      { effectId: "slow-reflex", kind: "modifier", modifierType: "penalty", targetStat: "reflex-save", value: -1, saveApplies: true },
      { effectId: "slow-speed", kind: "movement", value: 0.5, saveApplies: true, tags: ["half-speed"], rulesNote: "Movement speed is halved and rounded down to the next 5-foot increment." },
    ],
    counterspells: ["haste"],
    rulesSummary: "Slows one creature per caster level. Failed Will saves restrict actions, impose -1 to attacks, AC, and Reflex saves, and halve movement speed.",
    specialRules: ["Multiple slow effects do not stack.", "Slow counters and dispels haste."],
    sources: [srd("Slow")],
    tags: ["core", "srd", "arcane", "debuff", "action-economy", "speed"],
  },
  {
    id: "invisibility",
    name: "Invisibility",
    edition: "3.5e",
    school: "illusion",
    subschool: "glamer",
    classAccess: [
      access("bard", 2, "arcane", srd("Invisibility")),
      access("sorcerer", 2, "arcane", srd("Invisibility")),
      access("wizard", 2, "arcane", srd("Invisibility")),
    ],
    domainAccess: [{ domainId: "trickery", level: 2, source: srd("Trickery Domain") }],
    castingTime: { kind: "standard" },
    components: [
      { kind: "V", required: true },
      { kind: "S", required: true },
      commonMaterial("Arcane non-costly material component; normally supplied by a spell component pouch."),
      { kind: "DF", required: true, appliesToTradition: "divine", alternativeGroup: "m-or-df" },
    ].map((component) => component.kind === "M" ? { ...component, appliesToTradition: "arcane" as const, alternativeGroup: "m-or-df" } : component),
    range: { kind: "special", text: "Personal or touch" },
    targeting: { delivery: ["personal", "melee_touch", "target"], targetText: "You, or a touched creature or object weighing no more than 100 lb. per caster level", lineOfEffectRequired: true, lineOfSightRequired: false, objectAllowed: true },
    duration: { kind: "minutes_per_level", dismissible: true },
    savingThrow: { type: "will", outcome: "harmless", harmless: true, object: true, text: "Harmless Will save for creatures or objects when a save applies." },
    spellResistance: { applies: true, harmless: true, object: true },
    attackRoll: "none",
    effects: [
      { effectId: "invisible", kind: "condition", conditionId: "invisible", tags: ["concealment", "breaks-on-attack"] },
    ],
    permanencyEligible: true,
    rulesSummary: "Makes the subject and carried gear invisible. The effect ends if the subject attacks a foe, while many non-attack actions do not break it.",
    specialRules: [
      "Items dropped become visible; items picked up can disappear when carried appropriately.",
      "The spell is not silence and does not prevent indirect detection.",
      "An attack for this spell includes hostile spells that target a foe or include a foe in their area or effect.",
      "Permanency can make invisibility permanent on objects only.",
    ],
    sources: [srd("Invisibility"), srd("Trickery Domain")],
    tags: ["core", "srd", "arcane", "divine-domain", "illusion", "stealth", "condition"],
  },
  {
    id: "hold-person",
    name: "Hold Person",
    edition: "3.5e",
    school: "enchantment",
    subschool: "compulsion",
    descriptors: ["mind-affecting"],
    classAccess: [
      access("bard", 2, "arcane", srd("Hold Person")),
      access("cleric", 2, "divine", srd("Hold Person")),
      access("sorcerer", 3, "arcane", srd("Hold Person")),
      access("wizard", 3, "arcane", srd("Hold Person")),
    ],
    castingTime: { kind: "standard" },
    components: [
      { kind: "V", required: true },
      { kind: "S", required: true },
      { kind: "F", required: true, appliesToTradition: "arcane", alternativeGroup: "f-or-df", description: "Small straight iron focus.", itemTags: ["hold-person-focus"] },
      { kind: "DF", required: true, appliesToTradition: "divine", alternativeGroup: "f-or-df" },
    ],
    range: { kind: "medium", baseFeet: 100, feetPerCasterLevel: 10 },
    targeting: { delivery: ["target"], targetText: "One humanoid creature", lineOfEffectRequired: true, lineOfSightRequired: true, creatureTypes: ["humanoid"], objectAllowed: false },
    duration: { kind: "rounds_per_level", dismissible: true, text: "1 round/level; subject can attempt another save each round as described by the spell." },
    savingThrow: { type: "will", outcome: "negates", repeated: true, text: "Will negates initially; on each of its turns the subject may spend a full-round action to attempt another Will save to end the effect." },
    spellResistance: { applies: true },
    attackRoll: "none",
    effects: [
      { effectId: "hold-paralysis", kind: "condition", conditionId: "paralyzed", saveApplies: true, spellResistanceApplies: true, tags: ["humanoid-only", "repeat-save"] },
    ],
    rulesSummary: "Paralyzes one humanoid on a failed Will save. The subject remains aware but cannot act or speak and may spend a full-round action each turn attempting another Will save to end the effect.",
    specialRules: ["A paralyzed winged creature cannot flap its wings; a paralyzed swimmer cannot swim."],
    sources: [srd("Hold Person")],
    tags: ["core", "srd", "arcane", "divine", "mind-affecting", "paralysis", "control", "humanoid"],
  },
  {
    id: "web",
    name: "Web",
    edition: "3.5e",
    school: "conjuration",
    subschool: "creation",
    classAccess: [
      access("sorcerer", 2, "arcane", srd("Web")),
      access("wizard", 2, "arcane", srd("Web")),
    ],
    castingTime: { kind: "standard" },
    components: [
      { kind: "V", required: true },
      { kind: "S", required: true },
      commonMaterial("Non-costly material component; normally supplied by a spell component pouch."),
    ],
    range: { kind: "medium", baseFeet: 100, feetPerCasterLevel: 10 },
    targeting: { delivery: ["effect", "spread"], effectText: "Webs in a 20-foot-radius spread", radiusFeet: 20, lineOfEffectRequired: true, lineOfSightRequired: false, objectAllowed: true },
    duration: { kind: "ten_minutes_per_level", dismissible: true },
    savingThrow: { type: "reflex", outcome: "special", text: "Reflex determines whether a creature is immobilized by the initial web; even a successful save leaves the creature entangled while in the web." },
    spellResistance: { applies: false },
    attackRoll: "none",
    effects: [
      { effectId: "web-entangle", kind: "condition", conditionId: "entangled", saveApplies: true, tags: ["area-control"] },
      { effectId: "web-immobilize", kind: "control", saveApplies: true, tags: ["strength-check", "escape-artist", "movement"] },
      { effectId: "web-cover", kind: "special", tags: ["cover", "total-cover"], rulesNote: "Sufficient web between creatures provides cover or total cover as described by the spell." },
      { effectId: "web-fire", kind: "damage", damageType: "fire", dice: "2d4", tags: ["conditional", "burning-web"] },
    ],
    permanencyEligible: true,
    rulesSummary: "Creates a 20-foot-radius spread of sticky webs that entangle creatures and can immobilize them on a failed Reflex save. Escaping and movement use Strength or Escape Artist checks; the webs can burn.",
    specialRules: [
      "The web must be anchored to two or more solid and diametrically opposed points or it collapses and disappears.",
      "A creature that succeeds on the initial Reflex save is still entangled while in the web but is not initially fixed in place.",
      "Fire burns away sections of web and deals 2d4 fire damage to creatures in the burning portion.",
      "Permanency can make web permanent.",
    ],
    sources: [srd("Web")],
    tags: ["core", "srd", "arcane", "battlefield-control", "entangled", "movement", "flammable"],
  },
];

export const DND35_CORE_SRD_COMBAT_SPELLS_BY_ID = new Map(
  DND35_CORE_SRD_COMBAT_SPELLS.map((spell) => [spell.id, spell]),
);
